flask_skeleton_simple/skeleton/models/__init__.py
#
# __init__.py - base model classes
#

flask_skeleton_simple/skeleton/models/user.py
# copyright: (c) 2012 by Josef Skladanka <jskladan@redhat.com>, some content borrowed from Tim Flink <tflink@redhat.com>
# license: BSD, see LICENSE for more details.

from skeleton import db
from flask.ext.login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    pw_hash = db.Column(db.String(120), unique=False)

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def __repr__(self):
        return '<User %r>' % self.username

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pw_hash, password)

flask_skeleton_simple/skeleton/__init__.py
# copyright: (c) 2012 by Josef Skladanka <jskladan@redhat.com>, some content borrowed from Tim Flink <tflink@redhat.com>
# license: BSD, see LICENSE for more details.

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.sqlalchemy import SQLAlchemy

import logging
import os


logging.basicConfig(level=logging.INFO,
                    format='[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s',
                    datefmt='%Y%m%d-%H:%M%p')

# Flask App
app = Flask(__name__)
app.secret_key = 'not-really-a-secret'

# load default configuration
if os.getenv('DEV') == 'true':
    app.config.from_object('skeleton.config.DevelopmentConfig')
elif os.getenv('TEST') == 'true':
    app.config.from_object('skeleton.config.TestingConfig')
else:
    if app.secret_key == 'not-really-a-secret':
        raise Warning("You need to change the app.secret_key value for production")
    app.config.from_object('skeleton.config.ProductionConfig')


# setup logging
if app.debug:
    logging.basicConfig(level=logging.DEBUG,
                       format='[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s',
                       datefmt='%Y%m%d-%H:%M%p')


app.logger.debug('using DBURI: %s' % app.config['SQLALCHEMY_DATABASE_URI'])

# database 
db = SQLAlchemy(app)

# setup login manager
login_manager = LoginManager()
login_manager.setup_app(app)
login_manager.login_view = 'login_page.login'

# register blueprints
from skeleton.controllers.main import main
app.register_blueprint(main)

from skeleton.controllers.login_page import login_page
app.register_blueprint(login_page)

from skeleton.controllers.admin import admin
app.register_blueprint(admin)

flask_skeleton_simple/skeleton/controllers/admin.py
# copyright: (c) 2012 by Josef Skladanka <jskladan@redhat.com>, some content borrowed from Tim Flink <tflink@redhat.com>
# license: BSD, see LICENSE for more details.

from flask import Blueprint, render_template, flash, url_for
from flask.ext.login import login_required


admin = Blueprint('admin', __name__)

@admin.route('/admin')
@admin.route('/admin/')
@login_required
def admin_index():
    return render_template('admin/index.html')

flask_skeleton_simple/skeleton/controllers/login_page.py
# copyright: (c) 2012 by Josef Skladanka <jskladan@redhat.com>, some content borrowed from Tim Flink <tflink@redhat.com>
# license: BSD, see LICENSE for more details.


from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask.ext.wtf import Form, TextField, PasswordField, HiddenField
from flask.ext.login import login_user, logout_user, login_required, current_user, AnonymousUser


from skeleton import app, login_manager
from skeleton.models.user import User

login_page = Blueprint('login_page', __name__)


class LoginForm(Form):
    username = TextField(u'Username')
    password = PasswordField(u'Password')
    next_page = HiddenField()


# handle login stuff
@login_manager.user_loader
def load_user(userid):
    app.logger.debug("getting info for user %s" % str(userid))
    user = User.query.get(userid)
    if user:
        return user
    else:
        return AnonymousUser


@login_page.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()

    if login_form.validate_on_submit():
        user = User.query.filter_by(username = login_form.username.data).first()
        if user and user.check_password(login_form.password.data):
            login_user(user)

            app.logger.info('Successful login for user %s' % login_form.username.data)
            flash('Logged In Successfully!')

            return redirect(login_form.next_page.data)
        else:
            app.logger.info('FAILED login for user %s' % login_form.username.data)
            flash('Login Failed! Please Try again!')

    login_form.next_page.data = request.args.get('next') or url_for('main.index')
    return render_template('login.html', form = login_form)


@login_page.route('/logout')
@login_required
def logout():
    app.logger.info('logout for user %s' % current_user.username)
    logout_user()
    flash('Logged Out Successfully!')
    return redirect(url_for('main.index'))

flask_skeleton_simple/skeleton/controllers/main.py
# copyright: (c) 2012 by Josef Skladanka <jskladan@redhat.com>, some content borrowed from Tim Flink <tflink@redhat.com>
# license: BSD, see LICENSE for more details.

from flask import Blueprint, render_template
from skeleton import app

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index')
def index():
    if app.debug:
        app.logger.debug('rendering index')


    return render_template('index.html', title = 'skeleton Main Page')

flask_skeleton_simple/skeleton/templates/_formhelpers.html
{% macro render_field(field) %}
  <th>{{ field.label }}</th>
  <td>{{ field(**kwargs)|safe }}</td>
  <td>
    {% for error in field.errors %}
       <span style="color: red;">{{error}}</span>
    {% endfor %}
  </td>
{% endmacro %}

flask_skeleton_simple/skeleton/templates/index.html
{% extends "layout.html" %}

{% block body %}

<h1>Welcome to the Project Skeleton!</h1>

<p>This is super-awesome page for the Flask Skeleton Project. You can try logging in (admin/admin), or accessing the  <a href="{{ url_for('admin.admin_index') }}">Admin interface</a>.</p>

{% endblock %}

flask_skeleton_simple/skeleton/templates/layout.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <title>{{ title|default('skeleton') }}</title>
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

 <div class="page">

  <div class="metanav">
  {% if current_user.is_authenticated() %}
    Welcome, {{ current_user.username }} | <a href="{{ url_for('login_page.logout') }}">Log out</a>
  {% else %}
    You are not logged in | <a href="{{ url_for('login_page.login') }}">Log in</a>
  {% endif %}
   </div>

  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% block body %}
  <h1> My First Flask Application! </h1>
  {% endblock %}

  {% block footer %}
  {% endblock %}
 </div>

</body>
</html

flask_skeleton_simple/skeleton/templates/login.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block body %}

<div class="twelve columns" id="login">
<form method="post" action="login">
    {{ form.csrf_token }}
    {{ form.next_page }}
    <table>
    <tr>
        {{ render_field(form.username) }}
    </tr>
    <tr>
        {{ render_field(form.password) }}
    </tr>
    <tr>
        <td>
        <input type="submit" value="Login"/>
        </td>
    </tr>
    </table>
</form>
</div>

{% endblock %}